### ISSUE TITLE
Audio player does not auto-play on iOS

### ISSUE THREAD

**Issue by lijamie98** [lijamie98/m4christ-mobile#5]

**Comment by samuelili** [comment]
reminded the user to click the play button.

See commit [1](https://github.com/lijamie98/m4christ-mobile/commit/45745df6424f3178ac2b9b4df873677a52beb7fc) & [2](https://github.com/lijamie98/m4christ-mobile/commit/547e3a8688dbcaa590da751c6dfa412e053b2042)
